apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backend-tests-dotnet-basic-fteyplyg 
  description: Secure Supply Chain Example for C# .Net 6.0 example with advanced continuous integration pipeline covering building, CVE scanning, security scanning, signatures, attestations, SLSA provenance and SBOM along with Gitops-based continuous deployment.   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used tssc-gitops as the grouping
    argocd/app-selector: tssc/gitops=backend-tests-dotnet-basic-fteyplyg
    backstage.io/kubernetes-id: backend-tests-dotnet-basic-fteyplyg 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: rhtap-rhdh-qe/backend-tests-dotnet-basic-fteyplyg
    quay.io/repository-slug: rhtap_qe/backend-tests-dotnet-basic-fteyplyg
  tags: ["net", "sscs", "sbom", "acs"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
 